#!/bin/bash
total 56
drwxr-xr-x 2 root root   308 Jun 11 02:55 .
drwxr-xr-x 6 root root   121 Jun 10 15:06 ..
-rwxr--r-- 1 root root    30 Jun 10 15:25 0-hello_world
-rw-r--r-- 1 root root    12 Jun 10 15:11 0-hello_world~
-rwxr--r-- 1 root root    29 Jun 10 15:38 1-confused_smiley
-rw-r--r-- 1 root root     0 Jun 10 15:19 1-confused_smiley~
-rwxr--r-- 1 root root    28 Jun 10 15:35 2-hellofile
-rw-r--r-- 1 root root     0 Jun 10 15:27 2-hellofile~
-rwxr--r-- 1 root root    39 Jun 10 15:45 3-twofiles
-rwxr--r-- 1 root root    29 Jun 10 22:58 4-lastlines
-rw-r--r-- 1 root root    17 Jun 10 22:57 4-lastlines~
-rwxr--r-- 1 root root    29 Jun 10 23:02 5-firstlines
-rwxr--r-- 1 root root    36 Jun 10 23:51 6-third_line
-rwxr--r-- 1 root root    99 Jun 11 02:24 7-file
-rw-r--r-- 1 root root 12288 Jun 11 01:27 .7-file.swp
-rw-r--r-- 1 root root     0 Jun 11 02:55 ls_cwd_content
-rw-r--r-- 1 root root    16 Jun 10 15:07 README.md
